INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Türk Hava Yolları', 'Havayolu', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Arçelik', 'Dayanıklı Tüketim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Ford Otosan', 'Otomotiv', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Vestel', 'Dayanıklı Tüketim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Turkcell', 'Telekom', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('LC Waikiki', 'Hazır Giyim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Garanti BBVA', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('BİM', 'Perakende – Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('İş Bankası', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Türk Telekom', 'Telekom', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Ziraat Bankası', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Akbank', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Yapı Kredi', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('BSH', 'Dayanıklı Tüketim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Vakıfbank', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Migros', 'Perakende – Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Opet', 'Perakende – Akaryakıt', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Ülker', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Petrol Ofisi', 'Perakende – Akaryakıt', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Aselsan', 'Teknoloji – Savunma', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Enerjisa', 'Elektrik Dağıtım', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Halkbank', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tofaş', 'Otomotiv', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Anadolu Efes', 'Alkollü İçecek', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Denizbank', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Şişe Cam', 'Cam', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Şok', 'Perakende – Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Doğuş Otomotiv', 'Otomotiv Dağıtım', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Sütaş', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Türk Tuborg', 'Alkollü İçecek', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('İGA', 'Havalimanı', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Pegasus', 'Havayolu', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Mavi', 'Hazır Giyim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Enka', 'İnşaat', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('TürkTraktör', 'Otomotiv', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Otokoç', 'Otomotiv Dağıtım', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Yayla', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('TEB', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('TAV', 'İnşaat – Havalimanı İşletme', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Brisa', 'Oto Lastik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tusaş', 'Havacılık – Savunma', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Koton', 'Hazır Giyim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Medical Park', 'Sağlık', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Pınar', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Yataş', 'Ev Mobilya', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Otokar', 'Otomotiv', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('KoçSistem', 'Bilişim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Do&Co', 'İkram', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Odeabank', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('SuperFresh', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Anadolu Sigorta', 'Sigorta', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Albaraka Türk', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Netlog', 'Lojistik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Beşiktaş', 'Futbol Kulübü', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Agesa', 'Sigorta', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Fenerbahçe', 'Futbol Kulübü', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Kordsa', 'Kimya', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Anadolu Hayat', 'Sigorta', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Ekol', 'Lojistik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Koçtaş', 'Perakende – Ev Geliştirme', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Aygaz', 'LPG Dağıtım', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Galatasaray', 'Futbol Kulübü', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Emlak Konut', 'GYO', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Carrefoursa', 'Perakende – Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Kervan', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Petlas', 'Oto Lastik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Logo', 'Bilişim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Teknosa', 'Perakende – Teknoloji', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Türkiye Sigorta', 'Sigorta', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Banvit', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Alternatifbank', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Borsa Istanbul', 'Borsa', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Aksigorta', 'Sigorta', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Vakko', 'Hazır Giyim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Aytemiz', 'Perakende – Akaryakıt', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tukaş', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Kent', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('TSKB', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Şekerbank', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Karsan', 'Otomotiv', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Trabzonspor', 'Futbol Kulübü', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('İndeks', 'Teknoloji Dağıtım', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Arena', 'Bilişim', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Sabiha Gökçen', 'Havalimanı', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Mars', 'Lojistik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Aktif Bank', 'Banka', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Arzum', 'Küçük Ev Aletleri', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tat', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Netaş', 'Telekomünikasyon', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Dardanel', 'Gıda', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('DYO', 'Kimya', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('İnci Akü', 'Otomotiv Yan Sanayi', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Bossa', 'Tekstil', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Doğtaş Kelebek', 'Ev Mobilya', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Yünsa', 'Tekstil', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Reysaş', 'Lojistik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Anadolu Isuzu', 'Otomotiv', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Karel', 'Telekomünikasyon', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Ege Seramik', 'İnşaat Malzemesi', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Kütahya Porselen', 'Sofra Eşyası', 1);
