--kaynak
--https://eforpatent.com.tr/en-degerli-100-turk-markasi/
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Evyap', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Naturelive', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Duru', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Bingo', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Peros', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Ersağ', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Viking', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Paksoy', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Eti Matik', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Molped', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('ABC', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Dalin', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Molfix', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Emotion', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Familia', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Papia', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Teno', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tex', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Mintax', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Aromel', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('İdil', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Arko', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Bioxin', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Otacı', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Biobelinda', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Activex', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Spumy', 'Temizlik', 1);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tropicana', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Schweppes', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tnuva', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Strauss', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Nescafe', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tassimo', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Starbucks', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Lipton', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Dilmah', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Elite', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Strauss', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Walls', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Ben & Jerry''s', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Carmel Agrexco', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Agrexco', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Coca-Cola', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Pepsi Co', 'Gıda', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Tommy Hilfiger', 'Giyim', 0);
INSERT INTO marka (marka, kategori, yerli_mi) VALUES ('Nike', 'Giyim', 0);
